title: Constness Java Plugin
exclude:
  - LICENSE
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    stylesdir: css
    icons: font
    idseparator: _
    source-highlighter: coderay