title: Constness Java Plugin
theme: jekyll-theme-slate
exclude:
  - LICENSE
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
#    icons: font
#    idseparator: _
#    stylesdir: css
#    source-highlighter: coderay